/**
 * Seed script -- run with:
 *   npx tsx src/db/seeds/seed.ts
 *
 * Creates sample data suitable for local development and manual testing.
 */

import { db, closeDatabase } from "../index.js";
import * as schema from "../schema.js";
import { generateId } from "../../utils/helpers.js";
import { logger } from "../../config/logger.js";

async function seed(): Promise<void> {
  logger.info("Seeding database...");

  // ------------------------------------------------------------------
  // 1. Test user
  // ------------------------------------------------------------------

  const userId = generateId();

  await db.insert(schema.users).values({
    id: userId,
    firebaseUid: "test-firebase-uid-001",
    email: "testuser@trendmetrics.dev",
    displayName: "Test User",
    photoUrl: "https://ui-avatars.com/api/?name=Test+User",
  });

  // ------------------------------------------------------------------
  // 2. Credit balance + signup bonus transaction
  // ------------------------------------------------------------------

  const initialBalance = 25;

  await db.insert(schema.userBalances).values({
    userId,
    balance: String(initialBalance),
  });

  await db.insert(schema.creditTransactions).values({
    userId,
    type: "signup_bonus",
    amount: String(10),
    balanceAfter: String(10),
    description: "Welcome bonus",
    status: "completed",
  });

  await db.insert(schema.creditTransactions).values({
    userId,
    type: "purchase",
    amount: String(15),
    balanceAfter: String(initialBalance),
    description: "Initial top-up",
    status: "completed",
    idempotencyKey: "seed-topup-001",
  });

  // ------------------------------------------------------------------
  // 3. Five sample canonical trends
  // ------------------------------------------------------------------

  const now = new Date();
  const oneHourAgo = new Date(now.getTime() - 60 * 60 * 1000);
  const twoDaysAgo = new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000);

  interface SeedTrend {
    id: string;
    canonicalTitle: string;
    aliases: string[];
    category: string;
    country: string;
    language: string;
    sourcePlatforms: string[];
    verificationStatus: "verified" | "unverified";
    evidenceLevel: "high" | "medium" | "low" | "confirmed";
    summary: string;
    momentumScore: string;
    confidenceScore: string;
    crossPlatformScore: string;
    commercialRelevanceScore: string;
    freshnessScore: string;
    whyRising: string;
    whoCares: string;
    commercialAngle: string;
    brandAngle: string;
    ecommerceAngle: string;
    contentAngle: string;
    risks: string;
    recommendedActions: string[];
    businessUseCases: string[];
    scoreExplanations: Record<string, string>;
    firstSeenAt: Date;
    lastVerifiedAt: Date;
  }

  const trends: SeedTrend[] = [
    {
      id: generateId(),
      canonicalTitle: "AI-Powered Personal Stylists",
      aliases: ["AI Fashion Advisor", "Virtual Stylist AI"],
      category: "Fashion & Beauty",
      country: "US",
      language: "en",
      sourcePlatforms: ["youtube", "tiktok", "instagram"],
      verificationStatus: "verified",
      evidenceLevel: "high",
      summary:
        "AI-powered personal styling apps are surging across social media, with creators showcasing outfit recommendations generated by machine learning models trained on individual style preferences.",
      momentumScore: "92.5000",
      confidenceScore: "88.0000",
      crossPlatformScore: "85.0000",
      commercialRelevanceScore: "95.0000",
      freshnessScore: "90.0000",
      whyRising:
        "Convergence of improved LLMs, fashion-tech investment, and creator economy interest in personalisation tools.",
      whoCares: "Fashion brands, e-commerce platforms, content creators, Gen-Z consumers.",
      commercialAngle: "Affiliate links, SaaS subscriptions, brand partnerships for sponsored outfit picks.",
      brandAngle: "Partner with AI styling platforms for branded capsule collections.",
      ecommerceAngle: "Integrate AI recommendations into product pages to increase average order value.",
      contentAngle: "Create 'AI styled my wardrobe for a week' challenge videos.",
      risks: "Accuracy concerns, body-image sensitivity, data privacy.",
      recommendedActions: [
        "Monitor top styling apps for partnership opportunities",
        "Create branded style quiz powered by AI",
        "Sponsor creator challenges around AI styling",
      ],
      businessUseCases: [
        "Fashion retail personalisation",
        "Creator monetisation tools",
        "Subscription box curation",
      ],
      scoreExplanations: {
        momentum: "High view-count growth on TikTok and YouTube over 7 days",
        confidence: "Verified via YouTube API and multiple creator posts",
        cross_platform: "Present on 3 major social platforms",
      },
      firstSeenAt: twoDaysAgo,
      lastVerifiedAt: oneHourAgo,
    },
    {
      id: generateId(),
      canonicalTitle: "Protein Coffee Trend",
      aliases: ["Proffee", "Protein Espresso"],
      category: "Food & Beverage",
      country: "US",
      language: "en",
      sourcePlatforms: ["tiktok", "instagram"],
      verificationStatus: "verified",
      evidenceLevel: "high",
      summary:
        "Protein-infused coffee drinks are gaining massive traction on TikTok with the hashtag #proffee amassing over 300M views.",
      momentumScore: "88.0000",
      confidenceScore: "82.0000",
      crossPlatformScore: "70.0000",
      commercialRelevanceScore: "90.0000",
      freshnessScore: "85.0000",
      whyRising:
        "Fitness culture meets coffee culture; easy to make at home with protein powder and cold brew.",
      whoCares: "CPG brands, coffee chains, fitness influencers, supplement companies.",
      commercialAngle: "Launch ready-to-drink protein coffee SKU.",
      brandAngle: "Co-brand with popular protein powder labels.",
      ecommerceAngle: "Bundle protein powder + cold brew kits.",
      contentAngle: "Recipe videos and taste-test comparisons.",
      risks: "Taste-quality perception, ingredient safety scrutiny.",
      recommendedActions: [
        "Develop RTD protein coffee product",
        "Partner with fitness creators for sampling campaigns",
      ],
      businessUseCases: [
        "New product development",
        "Influencer marketing campaigns",
      ],
      scoreExplanations: {
        momentum: "Rapid hashtag growth on TikTok",
        confidence: "Verified by multiple creator posts with high engagement",
      },
      firstSeenAt: twoDaysAgo,
      lastVerifiedAt: oneHourAgo,
    },
    {
      id: generateId(),
      canonicalTitle: "Retro Gaming Revival on Twitch",
      aliases: ["Retro Speedruns", "Classic Game Streams"],
      category: "Gaming",
      country: "US",
      language: "en",
      sourcePlatforms: ["twitch", "youtube", "x-twitter"],
      verificationStatus: "verified",
      evidenceLevel: "medium",
      summary:
        "Retro game streaming is experiencing a comeback with nostalgic titles from the 90s dominating Twitch categories.",
      momentumScore: "78.5000",
      confidenceScore: "75.0000",
      crossPlatformScore: "80.0000",
      commercialRelevanceScore: "65.0000",
      freshnessScore: "72.0000",
      whyRising: "Nostalgia cycle, affordable emulation hardware, speedrunning community growth.",
      whoCares: "Game publishers, peripheral manufacturers, streaming platforms.",
      commercialAngle: "Retro console bundles, branded overlays, merchandise.",
      brandAngle: "Sponsor retro gaming tournaments.",
      ecommerceAngle: "Sell curated retro hardware bundles on marketplace.",
      contentAngle: "Speedrun highlights and 'first time playing' reaction content.",
      risks: "IP/licensing complications, niche audience ceiling.",
      recommendedActions: [
        "Evaluate retro IP licensing deals",
        "Sponsor upcoming speedrun events",
        "Launch nostalgia-themed merch line",
      ],
      businessUseCases: [
        "Event sponsorship",
        "Merchandise licensing",
        "Content creation partnerships",
      ],
      scoreExplanations: {
        momentum: "Steady growth in Twitch viewership for retro categories",
        cross_platform: "Discussed across Twitch, YouTube, and X",
      },
      firstSeenAt: twoDaysAgo,
      lastVerifiedAt: oneHourAgo,
    },
    {
      id: generateId(),
      canonicalTitle: "Turkish Artisan Ceramics Boom",
      aliases: ["Handmade Turkish Pottery", "Iznik Revival"],
      category: "Home & Garden",
      country: "TR",
      language: "tr",
      sourcePlatforms: ["instagram", "trendyol", "hepsiburada"],
      verificationStatus: "unverified",
      evidenceLevel: "medium",
      summary:
        "Demand for handmade Turkish ceramics is surging both domestically and in export markets, driven by Instagram aesthetics and e-commerce accessibility.",
      momentumScore: "72.0000",
      confidenceScore: "68.0000",
      crossPlatformScore: "60.0000",
      commercialRelevanceScore: "80.0000",
      freshnessScore: "75.0000",
      whyRising: "Global interest in artisanal home decor, Instagram visual appeal, tourism rebound in Turkiye.",
      whoCares: "Home decor retailers, artisan cooperatives, tourism boards, export agencies.",
      commercialAngle: "Curated artisan marketplace with international shipping.",
      brandAngle: "Collaborate with ceramic artists for limited-edition collections.",
      ecommerceAngle: "List on Trendyol and Hepsiburada with premium photography.",
      contentAngle: "Behind-the-scenes kiln and painting process videos.",
      risks: "Scalability of handmade production, quality control at volume.",
      recommendedActions: [
        "Partner with Anatolian artisan cooperatives",
        "Set up cross-border e-commerce listings",
      ],
      businessUseCases: [
        "Cross-border e-commerce",
        "Cultural tourism tie-ins",
      ],
      scoreExplanations: {
        momentum: "Search volume increase on Trendyol for 'el yapimi seramik'",
        confidence: "Inferred from e-commerce listing growth",
      },
      firstSeenAt: twoDaysAgo,
      lastVerifiedAt: oneHourAgo,
    },
    {
      id: generateId(),
      canonicalTitle: "AI Code Assistants in Enterprise",
      aliases: ["Copilot for Enterprise", "AI Pair Programming"],
      category: "Technology",
      country: "US",
      language: "en",
      sourcePlatforms: ["youtube", "x-twitter", "google-search"],
      verificationStatus: "verified",
      evidenceLevel: "confirmed",
      summary:
        "Enterprise adoption of AI code assistants has accelerated, with major companies reporting 20-40% productivity gains in developer workflows.",
      momentumScore: "95.0000",
      confidenceScore: "92.0000",
      crossPlatformScore: "88.0000",
      commercialRelevanceScore: "98.0000",
      freshnessScore: "94.0000",
      whyRising:
        "Maturing LLM capabilities, competitive pressure, measurable ROI data from early adopters.",
      whoCares: "CTOs, developer tool companies, enterprise software vendors, VCs.",
      commercialAngle: "Enterprise SaaS licensing, training and consulting services.",
      brandAngle: "Position as innovation leader by publicly sharing adoption metrics.",
      ecommerceAngle: "Sell premium IDE extensions and team licenses.",
      contentAngle: "Publish case studies and ROI benchmarks.",
      risks: "Code quality concerns, security vulnerabilities in generated code, vendor lock-in.",
      recommendedActions: [
        "Run internal pilot program",
        "Publish developer productivity metrics",
        "Evaluate security review processes for AI-generated code",
        "Negotiate enterprise licensing deals",
      ],
      businessUseCases: [
        "Developer productivity",
        "Enterprise software licensing",
        "Technical consulting",
        "Security auditing services",
      ],
      scoreExplanations: {
        momentum: "Explosive growth in Google Search interest and X discussions",
        confidence: "Confirmed by public earnings calls and analyst reports",
        cross_platform: "Discussed on YouTube, X, and dominating Google Search trends",
        commercial_relevance: "Direct enterprise revenue impact",
      },
      firstSeenAt: twoDaysAgo,
      lastVerifiedAt: now,
    },
  ];

  for (const t of trends) {
    await db.insert(schema.canonicalTrends).values({
      id: t.id,
      canonicalTitle: t.canonicalTitle,
      aliases: t.aliases,
      category: t.category,
      country: t.country,
      language: t.language,
      sourcePlatforms: t.sourcePlatforms,
      verificationStatus: t.verificationStatus,
      evidenceLevel: t.evidenceLevel,
      summary: t.summary,
      momentumScore: t.momentumScore,
      confidenceScore: t.confidenceScore,
      crossPlatformScore: t.crossPlatformScore,
      commercialRelevanceScore: t.commercialRelevanceScore,
      freshnessScore: t.freshnessScore,
      whyRising: t.whyRising,
      whoCares: t.whoCares,
      commercialAngle: t.commercialAngle,
      brandAngle: t.brandAngle,
      ecommerceAngle: t.ecommerceAngle,
      contentAngle: t.contentAngle,
      risks: t.risks,
      recommendedActions: t.recommendedActions,
      businessUseCases: t.businessUseCases,
      scoreExplanations: t.scoreExplanations,
      firstSeenAt: t.firstSeenAt,
      lastVerifiedAt: t.lastVerifiedAt,
    });
  }

  // ------------------------------------------------------------------
  // 4. Trend sources (2-4 per trend)
  // ------------------------------------------------------------------

  interface SeedSource {
    trendId: string;
    platform: string;
    url: string;
    title: string;
    metrics: Record<string, string | number>;
    isAccessible: boolean;
  }

  const sources: SeedSource[] = [
    // Trend 0 - AI Stylists
    { trendId: trends[0]!.id, platform: "youtube", url: "https://youtube.com/watch?v=example1", title: "I Let AI Pick My Outfits for 7 Days", metrics: { views: 2_400_000, likes: 180_000 }, isAccessible: true },
    { trendId: trends[0]!.id, platform: "tiktok", url: "https://tiktok.com/@fashionai/video/example1", title: "AI Stylist Challenge", metrics: { views: 5_100_000, shares: 89_000 }, isAccessible: true },
    { trendId: trends[0]!.id, platform: "instagram", url: "https://instagram.com/p/example1", title: "AI styled my capsule wardrobe", metrics: { likes: 340_000, comments: 12_000 }, isAccessible: true },
    // Trend 1 - Protein Coffee
    { trendId: trends[1]!.id, platform: "tiktok", url: "https://tiktok.com/@proffee/video/example2", title: "Best Proffee Recipe", metrics: { views: 8_300_000, shares: 200_000 }, isAccessible: true },
    { trendId: trends[1]!.id, platform: "instagram", url: "https://instagram.com/p/example2", title: "My morning proffee routine", metrics: { likes: 420_000, comments: 15_000 }, isAccessible: true },
    // Trend 2 - Retro Gaming
    { trendId: trends[2]!.id, platform: "twitch", url: "https://twitch.tv/retrogamer/clip/example3", title: "Super Mario World Speedrun WR", metrics: { viewers_peak: 45_000, clip_views: 890_000 }, isAccessible: true },
    { trendId: trends[2]!.id, platform: "youtube", url: "https://youtube.com/watch?v=example3", title: "Why Retro Gaming is Back", metrics: { views: 1_800_000, likes: 95_000 }, isAccessible: true },
    { trendId: trends[2]!.id, platform: "x-twitter", url: "https://x.com/user/status/example3", title: "The retro gaming renaissance thread", metrics: { impressions: 2_100_000, retweets: 12_000 }, isAccessible: true },
    { trendId: trends[2]!.id, platform: "youtube", url: "https://youtube.com/watch?v=example3b", title: "Top 10 Retro Games to Stream in 2026", metrics: { views: 950_000, likes: 62_000 }, isAccessible: true },
    // Trend 3 - Turkish Ceramics
    { trendId: trends[3]!.id, platform: "instagram", url: "https://instagram.com/p/example4", title: "Handmade Iznik Plate Process", metrics: { likes: 180_000, saves: 45_000 }, isAccessible: true },
    { trendId: trends[3]!.id, platform: "trendyol", url: "https://trendyol.com/p/example4", title: "El Yapimi Seramik Tabak", metrics: { orders: 3_200, rating: 4.8 }, isAccessible: true },
    // Trend 4 - AI Code Assistants
    { trendId: trends[4]!.id, platform: "youtube", url: "https://youtube.com/watch?v=example5", title: "How AI Coding Assistants Changed Our Team", metrics: { views: 3_200_000, likes: 210_000 }, isAccessible: true },
    { trendId: trends[4]!.id, platform: "x-twitter", url: "https://x.com/user/status/example5", title: "Enterprise AI coding adoption thread", metrics: { impressions: 4_500_000, retweets: 28_000 }, isAccessible: true },
    { trendId: trends[4]!.id, platform: "google-search", url: "https://trends.google.com/trends/explore?q=ai+code+assistant", title: "Google Trends: ai code assistant", metrics: { interest_score: 95 }, isAccessible: true },
  ];

  for (const s of sources) {
    await db.insert(schema.trendSources).values({
      trendId: s.trendId,
      platform: s.platform,
      url: s.url,
      title: s.title,
      metrics: s.metrics,
      isAccessible: s.isAccessible,
      verifiedAt: oneHourAgo,
      searchFallbackUrl: `https://www.google.com/search?q=${encodeURIComponent(s.title)}`,
    });
  }

  // ------------------------------------------------------------------
  // 5. Sample audit log entries
  // ------------------------------------------------------------------

  const auditEntries = [
    {
      userId,
      action: "user_login",
      resourceType: "user",
      resourceId: userId,
      details: { method: "firebase" },
    },
    {
      userId,
      action: "trend_discover",
      resourceType: "trend_query",
      resourceId: generateId(),
      details: { platform_group: "social-media", category: "Fashion & Beauty", country: "US" },
    },
    {
      userId,
      action: "credit_topup",
      resourceType: "credit_transaction",
      resourceId: generateId(),
      details: { amount: 15 },
    },
    {
      userId,
      action: "deep_analysis",
      resourceType: "trend_report",
      resourceId: generateId(),
      details: { trendId: trends[0]!.id, cost: 3 },
    },
  ];

  for (const entry of auditEntries) {
    await db.insert(schema.auditLogs).values(entry);
  }

  logger.info("Seed completed successfully", {
    userId,
    trends: trends.length,
    sources: sources.length,
    auditEntries: auditEntries.length,
  });
}

seed()
  .then(() => closeDatabase())
  .then(() => process.exit(0))
  .catch((err) => {
    logger.error("Seed failed", { error: (err as Error).message, stack: (err as Error).stack });
    process.exit(1);
  });
